// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaw8kAbtnVlcyqUL304zB2D6h8QC2wP54',
    appId: '1:947393038252:web:3e9e3ee4208b9b68a4dc09',
    messagingSenderId: '947393038252',
    projectId: 'costine-e2f22',
    authDomain: 'costine-e2f22.firebaseapp.com',
    storageBucket: 'costine-e2f22.appspot.com',
    measurementId: 'G-YZBPB8R5BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21yeKh-44g7LdHGQS1eCfT3ghc3SuFTM',
    appId: '1:947393038252:android:c0a30e1b824e4adea4dc09',
    messagingSenderId: '947393038252',
    projectId: 'costine-e2f22',
    storageBucket: 'costine-e2f22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC02S3qK6WwNqdaMn9jRljhX152ih7tW-A',
    appId: '1:947393038252:ios:a025195028be52c4a4dc09',
    messagingSenderId: '947393038252',
    projectId: 'costine-e2f22',
    storageBucket: 'costine-e2f22.appspot.com',
    iosClientId: '947393038252-rb98ck0df8c6dj44d2tjprq40c9p0ehp.apps.googleusercontent.com',
    iosBundleId: 'com.example.costine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC02S3qK6WwNqdaMn9jRljhX152ih7tW-A',
    appId: '1:947393038252:ios:a025195028be52c4a4dc09',
    messagingSenderId: '947393038252',
    projectId: 'costine-e2f22',
    storageBucket: 'costine-e2f22.appspot.com',
    iosClientId: '947393038252-rb98ck0df8c6dj44d2tjprq40c9p0ehp.apps.googleusercontent.com',
    iosBundleId: 'com.example.costine',
  );
}
